# import json
# import os
# from dotenv import load_dotenv

# from services.prompt_builder import PromptBuilder
# from services.llm_service import LLMService
# from services.resume_generator import ResumeGenerator
# from services.template_engine import TemplateEngine


# def load_student(path: str):
#     with open(path, "r", encoding="utf-8") as f:
#         return json.load(f)


# def main():
#     load_dotenv()

#     api_key = os.getenv("OPENAI_API_KEY")
#     model = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")

#     student = load_student("data/student.json")

#     prompt_builder = PromptBuilder(
#         "prompts/resume_prompt.txt"
#     )

#     llm_service = LLMService(
#         api_key=api_key,
#         model=model
#     )

#     generator = ResumeGenerator(
#         prompt_builder,
#         llm_service
#     )

#     resume = generator.generate(
#         student,
#         "output/resume.json"
#     )

#     template_engine = TemplateEngine(
#         "templates/resume_template.md"
#     )

#     template_engine.render(
#         resume,
#         "output/resume.md"
#     )

#     print("Resume generated successfully!")


# if __name__ == "__main__":
#     main()

import json
import os
from dotenv import load_dotenv

from services.prompt_builder import PromptBuilder
from services.llm_service import LLMService
from services.resume_generator import ResumeGenerator
from services.template_engine import TemplateEngine


def load_student(path: str):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_resume(student_data: dict):
    """
    Generate resume from student data.

    Returns:
        dict: resume json generated by LLM
    """

    load_dotenv()

    api_key = os.getenv("OPENAI_API_KEY")
    model = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")

    prompt_builder = PromptBuilder(
        "prompts/resume_prompt.txt"
    )

    llm_service = LLMService(
        api_key=api_key,
        model=model
    )

    generator = ResumeGenerator(
        prompt_builder,
        llm_service
    )

    resume = generator.generate(
        student_data=student_data,
        output_json="output/resume.json"
    )

    template_engine = TemplateEngine(
        "templates/resume_template.md"
    )

    template_engine.render(
        resume,
        "output/resume.md"
    )

    return resume


def main():

    student = load_student(
        "data/student.json"
    )

    generate_resume(student)

    print("Resume generated successfully!")


if __name__ == "__main__":
    main()